version: "3"

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app

  composer:
    image: composer/composer
    command: composer install
    volumes:
      - ./:/app